### ISSUE TITLE
In Countries Activity - Text Repeating

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#761] opened 2017-06-04 05:38 UTC
In Countries Activity - Began to type out united states, it went crazy and began typing “u” over and over again. Also occurred when attempting to type Australia. Was able to type Libya successfully. See screenshot.
![20170529_142130](https://cloud.githubusercontent.com/assets/8785617/26759230/5a516128-48ad-11e7-83c2-c3d67b50a831.jpg)

**Comment by quozl** [comment] 2017-06-06 07:30
Duplicate of https://github.com/sugarlabs/countries-activity/issues/1 and https://github.com/sugarlabs/sugar/issues/755 ... please check for known issues before reporting new ones.

**Closed by quozl** 2017-06-06 07:30 UTC
