### ISSUE TITLE
configure: error: empy not detected despite being installed

### ISSUE THREAD

**Issue by kushagra414** [sugarlabs/sugar#896] opened 2019-12-31 11:10 UTC
# empy is required
Although I have installed empy `pip install empy` and `pip3 install empy`.
When I tried running `autogen.sh`, empy is required error keeps on showing.
```bash
checking for empy... no
checking for empy3... no
configure: error: empy is required
```

**Comment by aperezbios** [comment] 2019-12-31 17:13
The empy check is deficient, this is a known problem, as there is an incorrect assumption that a empy binary exists, in the existing check, which is distribution-centric. YOu don't specifiy whether you're compiling from HEAD or a released version of Sugar. Do you know which version you're trying to compile?

**Comment by aperezbios** [comment] 2019-12-31 17:22
Try this patch/diff https://pastebin.com/raw/9JEa6tic

**Comment by quozl** [comment] 2019-12-31 20:07
Duplicate of https://github.com/sugarlabs/sugar/issues/882.

I've asked for testing on that issue, and I'm waiting for a response.  Please get involved.

**Comment by aperezbios** [comment] 2019-12-31 20:09
The response you asked for is right under your nose.

**Comment by kushagra414** [comment] 2020-01-01 06:49
> Try this patch/diff https://pastebin.com/raw/9JEa6tic

The Path was bit different, However, it worked. :+1: 
Shouldn't this be the default configuration?

**Comment by quozl** [comment] 2020-01-01 07:14
That's great, thanks.  Yes, the default will change, but question is what to change.  See discussion in https://github.com/sugarlabs/sugar/issues/882 and contribute if you are able.

**Closed** 2020-03-04 00:47 UTC
