### ISSUE TITLE
[E] Stuck at ./autogen.sh

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#891] opened 2019-12-03 14:22 UTC
I am stuck at 
```
ss@ss-srevinsaju:~/repo/sugar$ ./autogen.sh
You should update your 'aclocal.m4' by running aclocal.
configure.ac:28: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for python version... 3.7
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for empy... no
checking for empy3... /usr/bin/empy3
./configure: line 2679: syntax error near unexpected token `SHELL,'
./configure: line 2679: `PKG_CHECK_MODULES(SHELL, gtk+-3.0)'

```
I don't know how to proceed after this. Any helps?

**Comment by aperezbios** [comment] 2019-12-03 16:36
The error is staring you in the face :) "AM_GLIB_GNU_GETTEXT not found in library" means you probably need to install gettext. Next time, try a quick search/Google for an error string you think might lead you in the right direction. I found the answer in about 15 seconds, this way.

**Comment by Aniket21mathur** [comment] 2019-12-03 18:06
Have you build the dependencies before?
If not please do it by using `sudo apt build-dep sugar`

**Comment by srevinsaju** [comment] 2019-12-03 18:43
@aperezbios @Aniket21mathur I am trying to figure out the correct documentation on installing the sugar as part of Google Code In. I read most of the markdown files. Because the README.md file located at the root of the directory makes the installation of sugar seem easy as pie. A however, 'never look before you leap' person like me just tried doing that code, but however didn't work. I tried installing your deb package from the apt repository, which eventually crashed my PC twice. To find the error out, I had to build it manually. 

I will try as said above and let you know!
Thanks for sugar!

**Comment by srevinsaju** [comment] 2019-12-03 18:53
@Aniket21mathur , i might have ignored this error:
```
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list

```
This is because I didn't add to sources.list

**Comment by srevinsaju** [comment] 2019-12-03 18:54
@Aniket21mathur will adding deb-src download all sources for other packages too?

**Comment by srevinsaju** [comment] 2019-12-03 20:02
> The error is staring you in the face :) "AM_GLIB_GNU_GETTEXT not found in library" means you probably need to install gettext. Next time, try a quick search/Google for an error string you think might lead you in the right direction. I found the answer in about 15 seconds, this way.

@aperezbios gettext is already installed, it rasises the same error. I have already install sucrose, so it was its dependency too

**Comment by aperezbios** [comment] 2019-12-03 20:52
You're probably missing the equivalent/complimentaery gettext-dev/devel package. The sucrose package wouldn't install this, since the -devel packages are not dependencies of sucrose, to the best of my knowledge.

**Comment by quozl** [comment] 2019-12-03 22:43
Yes, still missing some dependencies.  You should not hope to satisfy dependencies in this iterative fashion without deep knowledge or some standard list of dependencies to compare against.   An `apt build-dep` can give you a probably good enough standard list to begin with, but it is Ubuntu or Debian specific.

See also https://github.com/sugarlabs/sugar/issues/884.

Adding `deb-src` to your source list will download metadata about the other packages, but not the source of the packages.

**Comment by srevinsaju** [comment] 2019-12-04 06:02
@quozl thanks for the info on `deb-src` . that's the only step I didn't execute.

**Comment by srevinsaju** [comment] 2019-12-04 06:03
@aperezbios ohk, I am getting into groove with sucrose. thanks for the help (•‿•)

_Sent from my Galaxy Note2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by srevinsaju** [comment] 2019-12-04 06:23
@quozl @aperezbios the code with `deb-src` is installing a lot of dependencies now. A Suggestion, can we package another deb which installs the dependencies automatically, so only building is left for the power user?

**Comment by quozl** [comment] 2019-12-04 06:35
@srevinsaju, that's not in our scope; we don't mind what Debian developers do with respect to packaging, but they seem happy with "apt build-dep", and it doesn't seem unreasonable for someone to use it on Debian or the Ubuntu derivative of Debian.  If you would like Debian to further simplify installing build dependencies, contact them? :grin:

**Comment by srevinsaju** [comment] 2019-12-04 07:35
@quozl I can't run sucrose. I tried `sudo apt install sucrose` but it is not starting on my system. what is the next step?

**Comment by Aniket21mathur** [comment] 2019-12-04 07:52
@srevinsaju where are you stuck? what is the exact error you are getting? Please specify.

Whenever you ask a doubt please also include the related error/exception :grin:

**Comment by quozl** [comment] 2019-12-04 09:04
@srevinsaju, if the `apt` command is not starting, then best ask the Ubuntu or Debian projects about why; it's not something we're going to be experts at, but if you want to try, let us know what is shown when you type the `apt` command.

On the other hand, if you don't know what to do *after* the `apt` command has finished; log out and then log in with the Sugar desktop selected.  See https://github.com/sugarlabs/sugar/blob/master/docs/ubuntu.md

**Comment by srevinsaju** [comment] 2019-12-04 13:05
@Aniket21mathur @quozl  I installed sucrose sucessfully. After doing the apt install command. I tried logging out ad changing the Desktop Environment. On selecting sugar, entering password and logging in, sugar de does not start. It is stuck at the lockscreen, mouse allowed to move, lock screen is dim, can switch ttys, but to go back to my default DE, i have to restart. 

Any method to solve this. Basically it does not give any errors. I don't know how to take the log from sugar. Or is it the same system used by other DEs that sugar also use to write logs.
Thanks


Some System Details:


```
            .-/+oossssoo+/-.               ss@ss-srevinsaju 
        `:+ssssssssssssssssss+:`           ---------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 19.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: G31M-ES2C 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.3.0-19-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 11 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3196 (dpkg), 4 (flatpak), 9 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1366x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: KDE 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: KWin 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Arc-Dark 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Breeze Dark [KDE], Breeze-Dark [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Papirus-Dark [KDE], Papirus-Dark [GTK3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: konsole 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel Core 2 4300 (2) @ 1.800GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GT 610 
      -+sssssssssssssssssyyyssss+-         Memory: 1078MiB / 2989MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       


```

**Comment by srevinsaju** [comment] 2019-12-04 13:06
@quozl @Aniket21mathur is it a wayland error? It is similar to the error due to graphics cards on Ubuntu GNOME Wayland

**Comment by quozl** [comment] 2019-12-05 00:37
Sugar writes errors to `~/.sugar/default/logs/shell.log`, so you should look there.

I've reproduced on an Ubuntu 19.10 VM.  Here's the important part of what `shell.log` says;

```log
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jarabe/desktop/activitychooser.py", line 24, in <module>
    from sugar3.graphics.popwindow import PopWindow
ImportError: No module named popwindow
```

Please check and confirm you have the same ImportError.

The cause is mixing Sugar and Sugar Toolkit versions;

```log
root@eoan:~# dpkg-query -W python-sugar3
python-sugar3   0.116-4
root@eoan:~# dpkg-query -W python-jarabe
python-jarabe   0.112-6
root@eoan:~# █
```

Fix is to either downgrade _python-sugar3_ to 0.112, or upgrade _python-jarabe_ to 0.116.

Sugar does not use Wayland yet.

**Comment by srevinsaju** [comment] 2019-12-07 21:11
@quozl exactly, this is the error I am having!! thanks a million, at last sugar on Ubuntu 19.10.
should I make a PR on the sugar native build environment thingy, because the doc was unclear, and that caused all the issue, we could included the issue number in the Docs. thanks anyway

**Comment by quozl** [comment] 2019-12-08 20:46
I like documentation that is succinct, accurate, and non-repetitive, so that maintenance is minimised.  The documentation seems clear at the moment; please review it and get back to me here if you think it needs fixing;

* [Setup a development environment - Packaged Sugar](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#packaged-sugar) has a link to Using Sugar on Ubuntu.
* [Using Sugar on Ubuntu - Ubuntu 19.10 Eoan Ermine](https://github.com/sugarlabs/sugar/blob/master/docs/ubuntu.md#ubuntu-1910-eoan-ermine) does mention the known problem.

> PS: How to downgrade sugar or upgrade python-jarabe? I am stuck with that, it is causing interlinked dependecy errors. Sorry for taking your time :(

When I hit this, I would either downgrade the toolkit package, or remove all packages and use a native install.

Downgrade the toolkit package;

* downgrade python-sugar3 to the Ubuntu 19.04 version (add disco to sources.list, `apt update`, `apt install python-sugar3/disco`)
* repeat for any other packages made from the same source, most easily checked by looking for the same version number in `dpkg-query -W`,
* hold each package to prevent upgrade, `apt hold python-sugar3`

Remove all packages and use a native install;

* use apt to remove all the Sugar packages and dependencies, `apt remove sucrose`, `apt autoclean --purge`, search for packages with similar version or names,
* follow [Native Sugar](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#native-sugar).

**Comment by Saumya-Mishra9129** [comment] 2020-05-18 13:54
I tried testing Sugar at Ubuntu 19.10 , but stuck at `/usr/bin/python3: Error while finding module specification for 'jarabe.main' (ModuleNotFoundError: No module named 'jarabe')` . It seems like we are still unable to fix this still, as the only option we have now to use **Native Sugar** for Ubuntu 19.10.

**Comment by quozl** [comment] 2020-05-19 03:59
Thanks for looking.  On Ubuntu 19.10 the problem is Ubuntu's, not ours.  They accepted packages from Debian Testing into their _universe_ suite at a time that Debian Project were half way through critical changes; so they got Sugar 0.112 mixed with Toolkit 0.116, a fatal combination.  We are indeed unable to fix Ubuntu without someone working with the Ubuntu developers.  As Ubuntu 20.04 has been released, and does fix the problem by dropping Sugar entirely, we can stop thinking about Ubuntu 19.10.  Ubuntu 20.10 does have Sugar 0.117.  Now would be a great time to test Ubuntu 20.10, before it is released in about October.

The original problem reported in the issue title and opening comment is solved, so we can close this now.

**Closed by quozl** 2020-05-19 03:59 UTC
