### ISSUE TITLE
issue with acme_volume_alsa_new on 0.116

### ISSUE THREAD

**Issue by nullr0ute** [sugarlabs/sugar#904] opened 2020-01-30 14:58 UTC
Seeing the following crash, with python3 but not sure if that's related, in Fedora 32.

<pre>
** (main.py:1538): WARNING **: 14:32:06.718: Failed to load shared library 'libsugarext.so.0' referenced by the typelib: /lib64/libsugarext.so.0: undefined symbol: sugar_event_controller_get_state
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/jarabe/main.py", line 68, in <module>
    from jarabe.view import keyhandler
  File "/usr/lib/python3.8/site-packages/jarabe/view/keyhandler.py", line 26, in <module>
    from jarabe.model.sound import sound
  File "/usr/lib/python3.8/site-packages/jarabe/model/sound.py", line 31, in <module>
    class PlaybackSound(object):
  File "/usr/lib/python3.8/site-packages/jarabe/model/sound.py", line 32, in PlaybackSound
    _volume = SugarExt.VolumeAlsa.new(_PLAYBACK)
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate acme_volume_alsa_new: 'acme_volume_alsa_new': /lib64/libsugar-eventcontroller.so.0: undefined symbol: acme_volume_alsa_new (1)
</pre>

**Comment by rabbitholecomputing** [comment] 2020-01-30 16:25
@quozl , any thoughts on this?

**Comment by aperezbios** [comment] 2020-01-30 16:25
@quozl, any feedback/ideas here?

**Comment by ritjoe** [comment] 2020-01-30 21:16
very reminiscent of https://bugzilla.redhat.com/show_bug.cgi?id=1240147

**Comment by quozl** [comment] 2020-01-30 22:47
Why isn't `libsugarext.so.0` installed?  That's the cause of the whole message.

**Comment by nullr0ute** [comment] 2020-01-31 07:54
> `libsugarext`

It's there:
rpm -ql sugar-toolkit-gtk3| grep libsugarext
/usr/lib64/libsugarext.so.0
/usr/lib64/libsugarext.so.0.0.0

**Comment by ritjoe** [comment] 2020-01-31 19:59
On Thu, Jan 30, 2020 at 11:54:57PM -0800, Peter Robinson wrote:
>     libsugarext
> 
> It's there:
> rpm -ql sugar-toolkit-gtk3| grep libsugarext
> /usr/lib64/libsugarext.so.0
> /usr/lib64/libsugarext.so.0.0.0

But the error, as is the case in the bug to which I posted the link earlier, has to do with expecting but not finding it in /lib rather than at /usr/lib

```
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate                
acme_volume_alsa_new: 'acme_volume_alsa_new':                                   
/lib64/libsugar-eventcontroller.so.0: undefined symbol: acme_volume_alsa_new (1)
```

Which way round do the symlinks go these days in Fedora? I've got a Fedora-SoaS-Live-x86_64-27-1.6.iso I just booted up here to check what was happening then, and see /lib -> usr/lib 

Is Python not following the symlink?

Is O_NOFOLLOW used here in some way as to stop the symlink from resolving?

**Comment by quozl** [comment] 2020-01-31 20:06
Thanks.  Is `/lib64` a symbolic link to `/usr/lib64` or vice-versa?  I ask because the error mentions `/lib64` only.

> Failed to load shared library 'libsugarext.so.0' referenced by the typelib: /lib64/libsugarext.so.0: undefined symbol: sugar_event_controller_get_state

Next, are the symbols in the file rational?

```
objdump -T /lib64/libsugarext.so.0
```

In particular, is sugar_event_controller_get_state present?  If so, it should be undefined.  A reference only.  Then in another file should be the definition;

```
objdump -T /lib64/libsugar-eventcontroller.so.0
```

Paths used by Python can be verified using _strace(1)_.

**Comment by ritjoe** [comment] 2020-01-31 20:15
On Fri, Jan 31, 2020 at 12:06:10PM -0800, James Cameron wrote:
> Thanks. Is /lib64 a symbolic link to /usr/lib64 or vice-versa? I ask because
> the error mentions /lib64 only.
> 
>     Failed to load shared library 'libsugarext.so.0' referenced by the typelib:
>     /lib64/libsugarext.so.0: undefined symbol: sugar_event_controller_get_state
>

My mistake, but yes at least on this old SoaS I'm looking at, there is also the lib64 symlink: /lib64 -> usr/lib64

I agree that strace could be useful here, but, as for that and the rest, I'll have to leave that to those who have current Fedora builds at hand.

I'm still trying to sort out what hardening was done that broke the build in the earlier report, and how removing that hardening solved it.

**Comment by quozl** [comment] 2020-01-31 20:35
Peter, is acme_volume_alsa_new defined in libsugarext.so.0?

Thing is, the last error you showed suggests GObject Introspection is looking in the event controller shared object instead of the Sugarext shared object;

> gi.repository.GLib.Error: g-invoke-error-quark: Could not locate acme_volume_alsa_new: 'acme_volume_alsa_new': /lib64/libsugar-eventcontroller.so.0: undefined symbol: acme_volume_alsa_new (1)

For me, this symbol is in libsugarext.so.0, and can be tested interactively in python3;

```log
>>> from gi.repository import SugarExt
>>> SugarExt.VolumeAlsa.new(0)
<SugarExt.VolumeAlsa object at 0x7ffa4e73b230 (AcmeVolumeAlsa at 0x7ffa509dd180)>
>>> 
```

An _strace(1)_ of this test shows both libsugarext.so.0 and libsugar-eventcontroller.so.0 are opened.  The former is opened on the import, the latter on the call to _VolumeAlsa_.

I can't see why gi would be looking into libsugar-eventcontroller.so.0 for a symbol that is defined in libsugarext.so.0!  Some new gi restriction or regression that prevents library cascade?

Thanks Joe.  Same here.  Yesterday I built all the Sugar components and Fructose activities from _master_ branch and released versions on another distribution's "rawhide".  I didn't get anything like this.

**Comment by nullr0ute** [comment] 2020-02-01 08:31
> Thanks Peter. Is `/lib64` a symbolic link to `/usr/lib64` or vice-versa? I ask because the error mentions `/lib64` only.

With the usr move that happened in Fedora (around F-17 from memory) its lib64 -> usr/lib64

**Comment by nullr0ute** [comment] 2020-02-01 08:47
> My mistake, but yes at least on this old SoaS I'm looking at, there is also the lib64 symlink: /lib64 -> usr/lib64 I agree that strace could be useful here, but, as for that and the rest, I'll have to leave that to those who have current Fedora builds at hand. I'm still trying to sort out what hardening was done that broke the build in the earlier report, and how removing that hardening solved it.

Good hint, in the process of moving to python3 I did a bunch of cleanups and dropped the hardened flag removal. Putting that back gets us further (I'll file that issue as a separate bug).

For reference the hardened flags option adds the following for compiling and linking. I'm guessing something is getting optimised out possibly at linking time.

compile:
<pre>
*cc1_options:
+ %{!r:%{!fpie:%{!fPIE:%{!fpic:%{!fPIC:%{!fno-pic:-fPIE}}}}}}
</pre>

link:
<pre>
*self_spec:
+ %{!static:%{!shared:%{!r:-pie}}}
</pre>

**Comment by nullr0ute** [comment] 2020-02-01 08:52
Opened #905 for the other issue

**Comment by quozl** [comment] 2020-02-03 05:53
Sorry, those flags don't make any sense to me.  What do they evaluate to for cc and ld?  Can you identify which ones are responsible for the issue?

**Comment by srevinsaju** [comment] 2020-02-05 17:39
I ran into the same error recently :(

**Comment by quozl** [comment] 2020-02-06 01:26
That's interesting.  Was it on Arch?  Did it used to work before an upgrade of some package?

**Comment by srevinsaju** [comment] 2020-02-07 20:08
@quozl, it didn't exist previously when built last time.
I fixed the error by one of the following changes
* The previous build depended on `https://github.com/sugarlabs/sugar-toolkit-gtk3/archive/v0.116.tar.gz` 
But, after I lost some of files, I used Ballo Gyorgy's configuration of using 
`https://download.sugarlabs.org/sources/sucrose/glucose/sugar/sugar-0.116.tar.xz)`
This might be a possible cause of the error, but I am not sure if bot are fundamentally different. 
The SHA256's do not match:
```
7d0ec1619c3167cb32ccbbed1da2cb42e9c7846aff5c9a45a35085067590a09c  sugar-0.116.tar.xz (sugarlabs)
b52889a19e8e9d2710cf0b3cf36b5238a282dd7b45e55073aa679ff9eb84eeb3  v0.116.tar.gz (github)
```
This error did not occur, when I built on github release and not depend on sugarlabs version, possible cause.
* Remove extra flags used with `./autogen.sh`, I previously used 
```
./autogen.sh --sysconfdir=/etc \
              --disable-schemas-compile
``` 
following the old build module by Ballo Gyorgy, but after removing it, it seems to work

* Exporting some variables (idk why, it looks like a library related thing)
```
export CFLAGS=${CFLAGS/ -fno-plt}
export LDFLAGS=${LDFLAGS/,-z,now}
```
* clean clone 
* Remove the already made `Makefiles` which might had been causing some conflicts
* Use mandatorily `./autogen.sh --with-python3` or python2, but removing the flag gives me the same error again, idk why

**Comment by quozl** [comment] 2020-02-07 21:20
Thanks.  https://github.com/sugarlabs/sugar-toolkit-gtk3/archive/v0.116.tar.gz is the unprepared source from the repository.  https://download.sugarlabs.org/sources/sucrose/glucose/sugar/sugar-0.116.tar.xz is the prepared source made by `make dist`.  You should use the prepared source unless you add a call to `autogen.sh` and `make dist`.  You should not use `autogen.sh` with the prepared source, but instead use those flags with `configure`.  

`autogen.sh` runs `intltoolize`, `autoreconf`, then `configure`.

The Fedora package also calls `autoreconf` without calling `intltoolize`.  https://src.fedoraproject.org/rpms/sugar/blob/master/f/sugar.spec#_166  I'm not sure why.

My guess is that running `autoreconf` on the prepared source has side-effects, but I can't see how it alone would cause object modules to be missing from shared object libraries.  I suggest testing and iterating without touching the packaging systems.

**Comment by srevinsaju** [comment] 2020-02-07 21:24
I will test it again on the download.sugarlabs.org prepared version on Ubuntu 20.04 again, just to confirm, I wouldn't want to break the current working packages. Thanks, maybe that might bean issue to @nullr0ute too?

**Comment by quozl** [comment] 2020-02-07 21:33
@srevinsaju, if `autoreconf` is doing something strange, we might have to change our use of it, or push that problem upstream to the maintainers of `autoreconf`.

**Comment by srevinsaju** [comment] 2020-02-07 21:37
I remember on Fedora, when I installed the rpm, it didn't work at first due to some reason which I don't remember, possibly, I assumed its my mistake and proceeded to the native build method.

**Comment by ethanhart2002** [comment] 2023-10-04 19:20
Should this issue be closed? Has this issue been present in any recent distributions of Fedora?

**Comment by quozl** [comment] 2023-10-04 19:32
I've no idea.  It looks likely to have been a Fedora problem.  I'll close until we hear otherwise.

**Closed by quozl** 2023-10-04 19:32 UTC
